[tool.mypy]
strict = false

[tool.ruff]
extend-select = [
    "F", 
    "A", 
    "B", 
    "INP", 
    "I", 
    "PYI", 
    "RSE", 
    "RET", 
    "Q", 
    "SLF", 
    "SIM", 
    "TID", 
    "TCH", 
    "ARG", 
    "PL", 
    "RUF",
    "C4",
    "G",
    "COM",
    "BLE",
    "FBT"
]
ignore = ["E501", "BLE001", "INP001", "PLR2004"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
show-fixes = true
target-version = "py311"